// <auto-generated />
using System;
using FlightPlannerFinal.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlightPlannerFinal.Migrations
{
    [DbContext(typeof(FlightPlannerDbContext))]
    partial class FlightPlannerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FlightPlannerFinal.Models.AirportRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Airport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("FlightPlannerFinal.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArrivalTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartureTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("carrier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("fromId")
                        .HasColumnType("int");

                    b.Property<int?>("toId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("fromId");

                    b.HasIndex("toId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("FlightPlannerFinal.Models.Flight", b =>
                {
                    b.HasOne("FlightPlannerFinal.Models.AirportRequest", "from")
                        .WithMany()
                        .HasForeignKey("fromId");

                    b.HasOne("FlightPlannerFinal.Models.AirportRequest", "to")
                        .WithMany()
                        .HasForeignKey("toId");

                    b.Navigation("from");

                    b.Navigation("to");
                });
#pragma warning restore 612, 618
        }
    }
}
